# Generated by Django 3.1 on 2020-08-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200821_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='imagem',
            field=models.ImageField(upload_to='clients_photos'),
        ),
    ]
